name: Run Jupyter Notebooks and Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert jupyter pandas numpy matplotlib seaborn scikit-learn easyocr
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic

    - name: Run Jupyter Notebooks
      run: |
        mkdir -p output
        find . -name "*.ipynb" -print0 | while IFS= read -r -d '' notebook; do
          jupyter nbconvert --to html --output-dir output --execute "$notebook"
          jupyter nbconvert --to pdf --output-dir output --execute "$notebook"
        done

    - name: Create index.html
      run: |
        echo "<html><body><h1>Index of Notebook Outputs</h1><ul>" > output/index.html
        for file in output/*.html; do
          filename=$(basename "$file")
          pdfname="${filename%.html}.pdf"
          if [ "$filename" != "index.html" ]; then
            echo "<li><a href=\"$filename\">$filename</a> (<a href=\"$pdfname\">PDF</a>)</li>" >> output/index.html
          fi
        done
        echo "</ul></body></html>" >> output/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
